name: todo_app
description: A simple to-do application demonstrating MVVM with Riverpod and go_router.
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  go_router: ^5.0.0
  ui_elements:
    path: ../ui_elements
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true